routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('question', 'QuestionsController')->except('show');
Route::get('/question/{slug}', 'QuestionsController@show')->name('question.show');
Route::resource('question.answers', 'AnswersController')->except(['index', 'create', 'show']);
Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use VoteableTrait;

    protected $fillable = ['body', 'user_id'];

    public function question()
    {
      return $this->belongsTo(Question::class);
    }

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function isBest()
    {
        return $this->id === $this->question->best_answer_id;
    }

    public function getBodyHtmlAttribute()
    {
      return clean($this->body);
    }

    public function getCreatedDateAttribute()
    {
      return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public static function boot()
    {
      parent::boot();

      static::created(function($answer)
      {
        $answer->question->increment('answers_count');
      });

      static::deleted(function($answer)
      {
        $answer->question->decrement('answers_count');
      });
    }
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question, Request $request)
    {
        $question->answers()->create($request->validate([
            'body' => 'required'
        ]) + [
            'user_id' => \Auth::id(),
        ]);

        return back()->with(['success' => 'Your Answer has been submitted successfully']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);

        return view('answers.edit', compact('question', 'answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);

        $answer->update($request->validate([
            'body' => 'required',
        ]));

        return redirect()->route('question.show', $question->slug)->with('success', 'Your answer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete', $answer);

        $answer->delete();

        return back()->with('success', 'Your answer has been removed');
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
        <div class="card-body">
            <div class="card-title">
                <h3>Your Answer</h3>
            </div>
            <hr>
            <form action="{{ route('question.answers.store', $question->id) }}" method="post">
                @csrf
                <div class="form-group">
                    <textarea name="body" id="body" cols="30" rows="7" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}"></textarea>
                    @if ($errors->has('body'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('body') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-lg btn-outline-primary">
                        Submit
                    </button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
@if ($answersCount > 0)
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
            <div class="card-body">
                <div class="card-title">
                <h2>{{ $answersCount . ' ' . \Illuminate\Support\Str::plural('Answer', $answersCount) }}</h2>
                </div>
                <hr>
                @include('layouts._message')
                @foreach($answers as $answer)
                <div class="media">
                    @include('shared._vote', [
                        'model' => $answer
                    ])

                    <div class="media-body">
                    {!! $answer->body_html !!} <br>
                        <div class="row mt-3">
                            <div class="col-4">
                                <div class="ml-auto">
                                    @can('update', $answer)
                                    <a href="{{ route('question.answers.edit', [$question->id, $answer->id]) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                    @endcan

                                    @can('delete', $answer)
                                    <form class="form-delete" action="{{ route('question.answers.destroy', [$question->id, $answer->id]) }}" method="post">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" name="button" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</button>
                                    </form>
                                    @endcan
                                </div>
                            </div>
                            <div class="col-4">

                            </div>
                            <div class="col-4">
                                @include('shared._author', [
                                    'model' => $answer,
                                    'label' => 'Answered'
                                ])
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                @endforeach
            </div>
            </div>
        </div>
    </div>
@endif

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h1>
                        Editing answer from question: <strong>{{ $question->title }}</strong>
                    </h1>
                </div>
                <hr>
                <form action="{{ route('question.answers.update', [$question->id, $answer->id]) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <textarea name="body" id="body" cols="30" rows="7" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">{{ old('body', $answer->body) }}</textarea>
                        @if ($errors->has('body'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('body') }}</strong>
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary">
                            Update
                        </button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection