routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('question', 'QuestionsController')->except('show');
Route::get('/question/{slug}', 'QuestionsController@show')->name('question.show');
Route::resource('question.answers', 'AnswersController')->except(['index', 'create', 'show']);
Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Question.php
<?php

namespace App;

use Str;
use App\User;
use App\Answer;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use VoteableTrait;

    protected $fillable = ['title', 'body'];

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function answers()
    {
      return $this->hasMany(Answer::class)->orderBy('votes_count', 'desc');
    }

    public function favorites()
    {
      return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }

    public function isFavorited()
    {
        return $this->favorites()->where('user_id', Auth()->id())->count() > 0;
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }

    public function setTitleAttribute($value)
    {
      $this->attributes['title'] = $value;
      $this->attributes['slug'] = Str::slug($value);
    }

    // public function setBodyAttribute($value)
    // {
    //     $this->attributes['body'] = clean($value);
    // }

    public function getUrlAttribute()
    {
      return route('question.show', $this->slug);
    }

    public function getCreatedDateAttribute()
    {
      return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
      if ($this->answers_count > 0) {
        if($this->best_answer_id){
            return 'answered-accepted';
        }
        return 'answered';
      }
      return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
      return clean($this->body);
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\AskQuestionRequest;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::with('user')->latest()->paginate(5);

        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();

        return view('questions.create', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
        $request->user()->questions()->create($request->all());

        return redirect()->route('question.index')->with('success', 'Your Question has been submitted.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $questions
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views');

        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $questions
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $this->Authorize('update', $question);
        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $questions
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        $this->Authorize('update', $question);
        $question->update($request->only('title', 'body'));

        return redirect()->route('question.index')->with('success', 'Your Question has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $questions
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $this->Authorize('delete', $question);
        $question->delete();

        return redirect()->route('question.index')->with('success', 'Your Question has been deleted.');
    }
}

resources/views/questions/_form.blade.php
@csrf
<div class="form-group">
  <label for="question-title">Question Title</label>
  <input type="text" name="title" value="{{ old('title', $question->title) }}" id="question-title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">

  @if($errors->has('title'))
    <div class="invalid-feedback">
      <strong> {{ $errors->first('title') }} </strong>
    </div>
  @endif
</div>
<div class="form-group">
  <label for="question-body">Explain You Question</label>
  <textarea name="body" id="question-body" rows="8" cols="80" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">{{ old('body', $question->body) }}</textarea>

  @if($errors->has('body'))
    <div class="invalid-feedback">
      <strong> {{ $errors->first('body') }} </strong>
    </div>
  @endif
</div>
<div class="form-group">
  <button type="submit" name="button" class="btn btn-outline-primary btn-lg">{{ $buttonText }}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <div class="d-flex align-items-center">
                    <h2>Ask Questions</h2>
                    <div class="ml-auto">
                      <a href="{{ route('question.index') }}" class="btn btn-outline-secondary">Back To All Questions</a>
                    </div>
                  </div>
                </div>

                <div class="card-body">
                  <form class="" action="{{ route('question.store') }}" method="post">
                    @include('questions._form', ['buttonText' => 'Ask Question'])
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <div class="d-flex align-items-center">
                    <h2>Edit Questions</h2>
                    <div class="ml-auto">
                      <a href="{{ route('question.index') }}" class="btn btn-outline-secondary">Back To All Questions</a>
                    </div>
                  </div>
                </div>

                <div class="card-body">
                  <form class="" action="{{ route('question.update', $question->id) }}" method="post">
                    {{ method_field('put') }}
                    @include('questions._form', ['buttonText' => 'Update Question'])
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <div class="d-flex align-items-center">
                    <h2>All Questions</h2>
                    <div class="ml-auto">
                      <a href="{{ route('question.create') }}" class="btn btn-outline-secondary">Ask Question</a>
                    </div>
                  </div>
                </div>

                <div class="card-body">
                  @include('layouts._message')

                  @forelse($questions as $question)
                    <div class="media">
                      <div class="d-flex flex-column counters">
                        <div class="vote">
                          <strong> {{ $question->votes_count }} </strong>
                          {{ \Illuminate\Support\Str::plural('vote', $question->votes_count) }}
                        </div>
                        <div class="status {{ $question->status }}">
                          <strong> {{ $question->answers_count }} </strong>
                          {{ \Illuminate\Support\Str::plural('answer', $question->answers_count) }}
                        </div>
                        <div class="view">
                          {{ $question->views ." ". \Illuminate\Support\Str::plural('view', $question->views) }}
                        </div>
                      </div>
                      <div class="media-body">
                        <div class="d-flex align-items-center">
                          <h3 class="mt-0">
                            <a href="{{ $question->url }}">  {{ $question->title }} </a>
                          </h3>
                          <div class="ml-auto">
                            @can('update', $question)
                              <a href="{{ route('question.edit', $question->id) }}" class="btn btn-sm btn-outline-info">Edit</a>
                            @endcan

                            @can('delete', $question)
                              <form class="form-delete" action="{{ route('question.destroy', $question->id) }}" method="post">
                                @method('delete')
                                @csrf
                                <button type="submit" name="button" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</button>
                              </form>
                            @endcan
                          </div>
                        </div>
                        <p class="lead">
                          Asked by
                          <a href="{{ $question->user->url }}"> {{ $question->user->name }} </a>
                          <small class="text-muted"> {{ $question->created_date }} </small>
                        </p>
                        {!! \Illuminate\Support\Str::limit($question->body_html, 250) !!}
                      </div>
                    </div><hr>
                  @empty
                    <div class="alert alert-warning">
                        <strong>Sorry</strong> There are no questions avaible.
                    </div>
                  @endforelse

                  {{ $questions->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                      <div class="d-flex align-items-center">
                        <h1>{{ $question->title }}</h1>
                        <div class="ml-auto">
                          <a href="{{ route('question.index') }}" class="btn btn-outline-secondary">Back To All Questions</a>
                        </div>
                      </div>
                    </div>

                    <hr>

                    <div class="media">
                        @include('shared._vote', [
                            'model' => $question
                        ])

                        <div class="media-body">
                            {!!  $question->body_html  !!} <br>
                            <div class="row mt-3">
                                <div class="col-4"></div>
                                <div class="col-4"></div>
                                <div class="col-4">
                                    @include('shared._author', [
                                        'model' => $question,
                                        'label' => 'Created'
                                    ])
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('answers._index', [
        'answers' => $question->answers,
        'answersCount' => $question->answers_count,
    ])
    @include('answers._create')
</div>
@endsection