routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('question', 'QuestionsController')->except('show');
Route::get('/question/{slug}', 'QuestionsController@show')->name('question.show');
Route::resource('question.answers', 'AnswersController')->except(['index', 'create', 'show']);
Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use VoteableTrait;

    protected $fillable = ['body', 'user_id'];

    public function question()
    {
      return $this->belongsTo(Question::class);
    }

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function isBest()
    {
        return $this->id === $this->question->best_answer_id;
    }

    public function getBodyHtmlAttribute()
    {
      return clean($this->body);
    }

    public function getCreatedDateAttribute()
    {
      return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public static function boot()
    {
      parent::boot();

      static::created(function($answer)
      {
        $answer->question->increment('answers_count');
      });

      static::deleted(function($answer)
      {
        $answer->question->decrement('answers_count');
      });
    }
}

app/Question.php
<?php

namespace App;

use Str;
use App\User;
use App\Answer;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use VoteableTrait;

    protected $fillable = ['title', 'body'];

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function answers()
    {
      return $this->hasMany(Answer::class)->orderBy('votes_count', 'desc');
    }

    public function favorites()
    {
      return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }

    public function isFavorited()
    {
        return $this->favorites()->where('user_id', Auth()->id())->count() > 0;
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }

    public function setTitleAttribute($value)
    {
      $this->attributes['title'] = $value;
      $this->attributes['slug'] = Str::slug($value);
    }

    // public function setBodyAttribute($value)
    // {
    //     $this->attributes['body'] = clean($value);
    // }

    public function getUrlAttribute()
    {
      return route('question.show', $this->slug);
    }

    public function getCreatedDateAttribute()
    {
      return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
      if ($this->answers_count > 0) {
        if($this->best_answer_id){
            return 'answered-accepted';
        }
        return 'answered';
      }
      return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
      return clean($this->body);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function questions()
    {
      return $this->hasMany(Question::class);
    }

    public function answers()
    {
      return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
      return $this->belongsToMany(Question::class, 'favorites')->withTimestamps();
    }

    public function voteQuestions()
    {
        return $this->morphedByMany(Question::class, 'voteable');
    }

    public function voteAnswers()
    {
        return $this->morphedByMany(Answer::class, 'voteable');
    }

    public function voteQuestion(Question $question, $vote)
    {
        $voteQuestions = $this->voteQuestions();
        $this->_vote($voteQuestions, $question, $vote);
    }

    public function voteAnswer(Answer $answer, $vote)
    {
        $voteAnswers = $this->voteAnswers();
        $this->_vote($voteAnswers, $answer, $vote);
    }

    private function _vote($relathionship, $model, $vote)
    {
        if ($relathionship->where('voteable_id', $model->id)->exists()) {
            $relathionship->updateExistingPivot($model, ['vote' => $vote]);
        }else{
            $relathionship->attach($model, ['vote' => $vote]);
        }

        $model->load('votes');
        $downVotes = (int) $model->downVotes()->sum('vote');
        $upVotes = (int) $model->upVotes()->sum('vote');

        $model->votes_count = $upVotes + $downVotes;
        $model->save();
    }

    public function getUrlAttribute()
    {
      // return route('question.show', $this->id);
      return '#';
    }

    public function getAvatarAttribute()
    {
      $email = $this->email;
      $size = 32;
      return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?s=" . $size;
    }
}

resources/views/shared/_accept.blade.php
@can('accept', $model)
    <a title="Mark this answer as best answer"
        class="{{ $model->status }} mt-2"
        onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $model->id }}').submit();"
    >
        <i class="fas fa-check fa-2x"></i>
    </a>
    <form id="accept-answer-{{ $model->id }}" action="{{ route('answers.accept', $model->id) }}" method="post" class="hide">
        @csrf
    </form>
@else
    @if ($model->is_best)
        <a title="The question owner accepted this answer as best answer"
            class="{{ $model->status }} mt-2"
        >
            <i class="fas fa-check fa-2x"></i>
        </a>
    @endif
@endcan

resources/views/shared/_author.blade.php
<span class="text-muted">{{ $label . ' ' . $model->created_date }}</span>
<div class="media mt-2">
<a href="{{ $model->user->url }}" class="pr-2">
    <img src="{{ $model->user->avatar }}" alt="">
</a>
<div class="media-body mt-1">
    <a href="{{ $model->user->url }}">
    {{ $model->user->name }}
    </a>
</div>
</div>

resources/views/shared/_favorite.blade.php
<a title="Click to mark as favorite {{ $name }} (Click again to undo)"
    class="favorite mt-2 {{ Auth::guest() ? 'off' : ($model->is_favorited ? 'favorited' : '') }}"
    onclick="event.preventDefault(); document.getElementById('favorite-{{ $name }}-{{ $model->id }}').submit();"
>
    <i class="fas fa-star fa-2x"></i>
    <span class="favorites-count">
        {{ $model->favorites_count }}
    </span>
</a>
<form id="favorite-{{ $name }}-{{ $model->id }}" action="/{{ $firstUriSegment }}/{{ $model->id }}/favorites" method="post" class="hide">
    @csrf
    @if ($model->is_favorited)
        @method('delete')
    @endif
</form>

resources/views/shared/_vote.blade.php
@if ($model instanceof App\Question)
    @php
        $name = 'question';
        $firstUriSegment = 'questions';
    @endphp
@elseif ($model instanceof App\Answer)
    @php
        $name = 'answer';
        $firstUriSegment = 'answers';
    @endphp
@endif

@php
    $formId = $name . '-' . $model->id;
    $formAction = "/{$firstUriSegment}/{$model->id}/vote";
@endphp
<div class="d-flex flex-column vote-controls">
    <a title="This {{ $name }} is usefull"
        class="vote-up {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('up-vote-{{ $formId }}').submit();"
    >
        <i class="fas fa-caret-up fa-3x"></i>
    </a>
    <form id="up-vote-{{ $formId }}" action="{{ $formAction }}" method="post" class="hide">
        @csrf
        <input type="hidden" name="vote" value="1">
    </form>

    <span class="votes-count">{{ $model->votes_count }}</span>

    <a title="This {{ $name }} is not usefull"
        class="vote-down {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('down-vote-{{ $formId }}').submit();"
    >
        <i class="fas fa-caret-down fa-3x"></i>
    </a>
    <form id="down-vote-{{ $formId }}" action="{{ $formAction }}" method="post" class="hide">
        @csrf
        <input type="hidden" name="vote" value="-1">
    </form>

    @if ($model instanceof App\Question)
        @include('shared._favorite', [
            'model' => $model,
            'name' => $name
        ])
    @elseif ($model instanceof App\Answer)
        @include('shared._accept', [
            'model' => $model
        ])
    @endif
</div>